name: VN IP CIDR Generate

on:
  schedule:
    - cron: "11 10 * * */7"

jobs:
  generate_v4:
    name: Generate IPv4 CIDR list
    runs-on: ubuntu-latest
    steps:
      - name: Calculate version
        run: |
          echo "RELEASE_TAG_NAME=$(date +'%y.%m.%V')" >> $GITHUB_ENV
          echo "RELEASE_NAME=Week $(date +'%V') of $(date +'%Y') ($(date +'%B'))" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python PyPy 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "pypy3.10"
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirement.txt
      - name: Download raw IP ranges file
        run: wget https://suip.biz/?act=all-country-ip&country=VN&all-download -O tmp/VN-suip.biz.txt
      - name: Run generation script
        run: python main.py
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/vn_ipv4_cidr.txt
          tag_name: ${{ env.RELEASE_TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          draft: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}